version: "3"
services:
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - mysql:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./docker/production/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s puma -b 0.0.0.0 -p 3000 -e production"
    env_file: .env
    volumes:
      - bundle:/usr/local/bundle
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql:
  bundle:
